### ISSUE TITLE
After update to 4.0: epex_spot: cannot import name 'OptionsFlowWithReload'

### ISSUE THREAD

**Issue by rwese** [mampfes/ha_epex_spot#254]
I tried debugging it but can not find any cause on my end. Delete it all, look for any residual files, for grepped everything, re-install, same result. 🤷 

```
Logger: homeassistant.config_entries
Source: config_entries.py:3727
First occurred: 6:56:57 PM (3 occurrences)
Last logged: 6:57:00 PM

Error occurred loading flow for integration epex_spot: cannot import name 'OptionsFlowWithReload' from 'homeassistant.config_entries' (/usr/src/homeassistant/homeassistant/config_entries.py)
```
`Config flow could not be loaded: {"message":"Invalid handler specified"}`

This is triggered when I attempt adding a new integration.

<img width="618" height="311" alt="Image" src="https://github.com/user-attachments/assets/d77424ec-a8d2-4be2-b968-d014b086b950" />

**Comment by rwese** [comment]
@suaveolent everything is up to date, i rolled back to 3, remove all/reboot/reinstall.

will give it another go tomorrow.

**Comment by rwese** [comment]
I am very sorry... somehow the supervisor failed to fetch homeassistant updates, silently.
